Optimize the document for readability
k8snetworkplumbingwg/multus-cni pull request #1029
Opened 2023-02-06 06:29 UTC by Fish-pro

Optimize the document for readability

2023-02-13 16:17 UTC, dougbtv requested changes

2023-02-13 16:17 UTC, dougbtv commented on docs/configuration.md
> +Lets setup an example where we:
Remove this change. The others are good, but "let's" is a contraction of "let us" so it uses an apostrophe.

2023-02-20 03:25 UTC, Fish-pro commented
@dougbtv Could you please review it again？

2023-07-28 01:59 UTC, Fish-pro commented
/cc @dougbtv

2023-11-02 02:02 UTC, closed without merging