Move chroot from multus main process to its child processes
k8snetworkplumbingwg/multus-cni pull request #1161
Opened 2023-09-21 12:00 UTC by pliurh

We used to run chroot in multus main process when calling other CNI plugin binary. We also use a mutex to lock the access to pod files. But this causes performance issues when facing heavy CNI_ADD/CNI_DEL requests.

With this patch, we do chroot in the child processes instead. So file operations in the main process will not be affected by chroot.

This change requires the multus thick plugin pod to mount CNI bin directory to the same path in the container host.

fixes https://issues.redhat.com/browse/OCPBUGS-18995

2023-09-22 05:09 UTC, s1061123 commented
Thank you so much for great PR, @pliurh ! Overall desgin makes sense to me.

One minor comments but this PR implicitly requires to manifest to mount CNI bin directory to same path in container host. (e.g. if /opt/cni/bin is the CNI bin directory, multus-daemon pod has to mount it with same path /opt/cni/bin, not /opt/bin.
Could you write down in [thick-daemon manifest file](https://github.com/k8snetworkplumbingwg/multus-cni/blob/master/deployments/multus-daemonset-thick.yml) https://github.com/k8snetworkplumbingwg/multus-cni/blob/master/deployments/multus-daemonset-thick.yml?

2023-09-22 07:56 UTC, s1061123 requested changes

2023-09-22 07:56 UTC, s1061123 commented on deployments/multus-daemonset-thick.yml
> +            - name: cni-bin
Could you please add explicitly mentioned in comment? as

```
# multus-daemon expects that cni-bin path must be identical between pod and container host, 
# e.g. if cni bin is '/opt/cni/bin' in container host side, then it should be mount to '/opt/cni/bin' in multus-daemon,
# not other directory, as '/opt/bin' or '/usr/bin'.
```

2023-09-22 08:08 UTC, merged

2023-09-25 03:57 UTC, Deadpan110 commented
line 173 of deployments/multus-daemonset-thick.yml should be:

` - name: cnibin`
and not:
` - name: cni-bin`