Add config to support multusMasterCNI in Thick Plugin
k8snetworkplumbingwg/multus-cni pull request #1245
Opened 2024-03-15 23:08 UTC by raghs-aws

https://github.com/k8snetworkplumbingwg/multus-cni/issues/1237

2024-03-28 14:20 UTC, dougbtv requested changes

2024-03-28 14:20 UTC, dougbtv commented on docs/thick-plugin.md
> +In this case you can define your primary CNI conffile as ```multusMasterCNI``` as present in the ```multusAutoconfigDir```. This is helpful when you have multiple CNIs and in same usecases or race co
let's use a cloud agnostic name here `(10-cloudprovider.conflist)`

2024-03-28 14:20 UTC, dougbtv commented on docs/thick-plugin.md
> +        "multusMasterCNI": "10-aws.conflist"
this line too, thanks!

2024-04-01 13:48 UTC, raghs-aws commented
Added new changes as requested to refer cloud agnostic config as 10-cloudprovider.conflist

2024-08-16 02:22 UTC, closed without merging