always attempt a live pod get on miss to confirm its really not there
k8snetworkplumbingwg/multus-cni pull request #1332
Opened 2024-09-11 17:11 UTC by dougbtv

From [openshift pull request](https://github.com/openshift/multus-cni/pull/246):

> This makes sure that stale caches never result in NotFound errors.

It was explained to me that informers are almost always are more efficient, and in most cases will work, but a live lookup is appropriate after a number of failures.

This happens only on the retry portion, so we're still getting the benefits of informers, but, on a retry situation, we don't get a cache miss.

2024-09-12 13:37 UTC, s1061123 requested changes

2024-12-19 18:29 UTC, bpickard22 commented
/lgtm

2024-12-19 18:30 UTC, bpickard22 commented
bump to remove stale

2024-12-19 19:10 UTC, bpickard22 commented
name change looks good

2024-12-19 19:10 UTC, bpickard22 commented
/lgtm

2024-12-19 19:13 UTC, merged